### ISSUE TITLE
Contributor Disscusion

### ISSUE THREAD

**Issue by riddlez666** [ellaism/meta#20] opened 2018-02-24 13:14 UTC
List of contributor wallet signers:
- Shaman - 0xd047bb41e9acc7fd6d3e73c1f29153a6600fdc35
https://keybase.io/8shaman8/
https://explorer.ellaism.org/tx/0x966d8694d97f7c554bc8b459420b5c53c35396fa102d63debba2b36ea8ec3c7e

- vega40k - 0x00Ac1950a54e64fd36ec8562217a2Bfd5c07A3c3
https://keybase.io/vega40k/

- sncs - 0x00b10b9901216eFd5Dc50cd9f922D8aeFf9Ad904
https://keybase.io/sncs/

- iamthebeast - 0x00b7281DB201a00CbEEfC8F596569b0B1df540b7
https://keybase.io/iamabeast/

- osoese - 0x0666bf13ab1902de7dee4f8193c819118d7e21a6
https://keybase.io/osoese/
https://explorer.ellaism.org/tx/0x5a725e8ad45d572c1117b46b240bb7b7fbcafc1c0d68946567cb5483a0b13536

- riddlez666 - 0xc393659c2918a64CDfb44d463dE9c747Aa4Ce3f7
https://keybase.io/riddlez666/
https://explorer.ellaism.org/tx/0xa3a78f175da7d1b86afd0644e84b5bc168f6e9efbaf962d36cb75cb8e05f0fea

**Comment by riddlez666** [comment] 2018-02-24 13:23
yup was getting to that :) bit of a list to go thru this morning.

**Comment by riddlez666** [comment] 2018-02-24 13:32
@ellaismer one more missing but he will reply ASAP

**Comment by riddlez666** [comment] 2018-02-24 17:35
Updated.

**Comment by ellaismer** [comment] 2018-02-24 19:13
Thanks I'll get you the instructions soon!

**Comment by ellaismer** [comment] 2018-02-25 22:43
@riddlez666 I have deployed the multisig contract at [0xe3ecbf9ad12bf63b94fd4f7bc3dc7fcfc56e66ce](https://explorer.ellaism.org/account/0xe3ecbf9ad12bf63b94fd4f7bc3dc7fcfc56e66ce). There're two things left: a) test the multisig, and b) sign proofs and send it to blockchain.

###### Test Multisig

First you may want to send 0.1 ELLA or something like that to the above wallet for testing.

You can use the instruction in https://github.com/ellaism/meta/tree/master/multisig/deploy to validate that those contracts are of given source code. Please have at least one of the signers done the validation.

Next you'll need to use one of the browser plugin. If you are able to send transactions through Parity, that means installing the Parity Chrome Extension (https://chrome.google.com/webstore/detail/parity-ethereum-integrati/himekenlppkgeaoeddcliojfddemadig). After that, go to https://wallet.gnosis.pm/ it will tell you that you'd use a local version to be safer. Well, you can do that, or if it is too complicated, the online version is actually safe enough. Go to Settings, in "Ethereum node", choose "Local node", and in "web3 provider", choose "Default (MetaMask, Mist, Parity ...)".

After that, go back to "Wallets" tab, click "Add" to add a new wallet, choose "restore deployed wallet". Enter a name, and enter the community fund multisig address. After this, client the wallet and you'll go to the multisig management panel where you can see the current owners and current multisig transactions.

Next you would want to test sending money out. You can use a random address, and the above 0.1 ELLA for this purpose. If you see the "multisig transactions" to be empty, please click add, and enter transaction info for a test transaction. Otherwise, you can see the current mutlsig transactions with approval counts, and click confirm if this transaction is legit.

Note that multisig wallets can send transactions to itself, this means that transactions can add/remove owners, and change required approval counts. So please be careful and check everything is fine before you click confirm.

During this process, you might also need to go to https://127.0.0.1:8180/ for approving transactions in the signing ring. Change the gas price to 30000000000 for transactions to be confirmed in the next block.

###### Send Blockchain Proof

You should sign a PGP proof stating that you own the address you provided. Go to https://keybase.io/sign and enter a message like below. Feel free to change stuff but please make sure that a) you state who you are, b) your wallet address, c) the community multisig address:

```
I'm Ellaismer, Core Developer of Ellaism and @ellaismer at keybase.io, verifying my ownership of this Ellaism address 0x0058781f3A0C1a9BE51581CBD8BC41B871c37713 used for the Ellaism Dev Fund Multisig: 0xe9C2d958E6234c862b4AfBD75b2fd241E9556303
```

Please post the signed proof below.

Next we're going to publish this proof on the blockchain. If you use MetaMask, you can do this through MyEtherWallet but it has not yet been tested. Please let me know if you want to do this approach. If you are using Parity, please open two tabs to http://127.0.0.1:8180. For one of the tabs, go to "Applications", select "Parity/Web3 Console". In the bottom, input a command that I'll send you and press enter. Now go to the other tab, and confirm the transaction (remember to set a correct gas price). Please then post your transaction id.

If you want to generate the command yourself, here's the template:

```
web3.eth.sendTransaction({from:"<your address>",to:"<multisig wallet address>",value:"0x0",data:"<hex encoding of the proof your sent>"})
```

**Comment by riddlez666** [comment] 2018-02-26 21:33
"I'm riddlez666, Developer of Ellaism and @riddlez666 at keybase.io, verifying my ownership of this Ellaism address 0xc393659c2918a64cdfb44d463de9c747aa4ce3f7 used for the Ellaism Contributor Fund Multisig: 0xe3ecbf9ad12bf63b94fd4f7bc3dc7fcfc56e66ce"

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. 
kXR7VktZdyH7rvq v5weRa0zkOipO6L LsOSbe4FowtrGTT qYbUXB5Pm3wjC11 w2dXNIQLkcivZBP 9jEAEuF1gqkPu5m 2O9D3nkFEGKi746 pWyX906gFfrFdPn PILFavFZD4aSWoD 5O8UlkIYxzr79f0 Cfvh0xbdgcJYsEA jjHRCzqadTxds2L MqZvNRwNHIbHAhY vTCDOkfOQEBNRld 4D3fzQeSf93bA17 5WcR3FrqMG4JVAJ 9kOMLpJQPGgO9cj 2Z7RXJ0RaHtCKaT GotqOOw1GchoHlj ktuPw05vr91GWZs oRMjofEhtzr3jkH yKY5YxS9o7vvi3h kpMDbTbbQqqP3bC 95jvdyWq0R9XrV6 h1Fy82rBPwwpvmW JEVURLf3Z8ZFN37 1UqYtP2Wmp0Y60c HRhHYeIecRQeJrz M2TCvt8WYYRc0x8 nYWp15uMC9eUFqo tYjE1Uevx0FMG6z cwWSc6sgDbc24p1 QHI70SwpflB9UQW Mh3XVtQ2SB8zB5H QS7gdK6cP. 
END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by dabingus** [comment] 2018-02-27 01:46
"I'm Hunter, contributor wallet signer of Ellaism and verifying my ownership of this Ellaism address 0x00b7281DB201a00CbEEfC8F596569b0B1df540b7 used for the Ellaism Contributor Fund Multisig: 0xe3ecbf9ad12bf63b94fd4f7bc3dc7fcfc56e66ce"
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zk8tK7Ss TR5FGPUiHBMlrJR Jy3TGYXB3jCISov M8J3d7Rxd8HWJCb xvMYwjjnTmZyasM emRhzReY2yO0hLZ qg7ZQ68teKH6EMt ttbPtKeUyMQOiKB WWlDF3p0VOOUioA RPowCNkddWrS01b BzVaRxouJ3HMBIk efBL11KymtgC7iZ CQT0U7Z3DG3nbLd THgJ5R3u6xaHnh7 SZFReAwvwsvGd41 wKvinEMePOVdVF4 yxCO3TzW4dBlQs4 tbDeulA2vdmd8bV Nyrk7iraReUNzE7 wPhQAytgW60IQIC 1LOV6UWMRSxhr5X Ggit4i4ojCLcuZN ImfTwpXrbW9jbk2 CFVjdLJRF3l3uBM 8QauyMmq10RjR3u 4OdwrXvPhft8NY3 ucHFcRO7DSUlouv 80DPSQKsXtRqNGz WYU4HLlSVMNCwDV 4L85u8oFwXiFUUK arJqPVYa3WzqQNE CJaXOxcUxOnTuN1 yLY5. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by osoese** [comment] 2018-02-27 04:33
"I'm OSOESE Developer of Ellaism and @osoese at keybase.io, verifying my ownership of this Ellaism address 0x0666bf13ab1902de7dee4f8193c819118d7e21a6 used for the Ellaism Contributor Fund Multisig: 0xe3ecbf9ad12bf63b94fd4f7bc3dc7fcfc56e66ce"
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkEjQIBU hfKsphmcoGemN2V hxF8amlEf33Xr4j vRJz1cXXuUlirOV EubFgH8hRAhwaOE P1BmFWvvhP4fVEH uqATp8ggDFPfqa9 K1NtN4FQXXoU9GM Une8gce6RWliKQh PypT7yBcRuYDsYi NFFugS0A7I9KcIb 7vzcet8CSJGWGRw i21hKCWykN6cteO GsiatODT2y9I6Wn gULA7qFqsswZgzL Vq4r1euZ6ZqFucX f6rB0LpdRT3lY4E rnDcpdXFjWg6tMd fkMsOytx9ef6kYV QOl4fmL7dKt9N3l QEZkxM9ht3QGpyY yfGOLqQ6GMz0xWB fgdVhy300PDGw6A v3yxzQGlGAjNisd f8CQoqlpO2mzRMZ 3ndx1ISiVRY2YQG GoF7mUhTqmSOh9B csyBT9VryCGhtHv 1nArluAro1EwSIr in344alPJnRp8He od8DKRzH4NIEQyK HGUWg5jk8o2ILJe 6e3tsy9Eoskv. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by riddlez666** [comment] 2018-02-27 04:33
@ellaismer instructions unclear super glued head to table tonight..... the signing then to blockchain part.

**Comment by ellaismer** [comment] 2018-02-27 09:18
Okay looks like some of you are using the saltpack message format. When sending hex message on the blockchain using this, you can exclude the plaintext message part and only use the part between "BEGIN KEYBASE SALTPACK SIGNED MESSAGE." and "END KEYBASE SALTPACK SIGNED MESSAGE."

**Comment by ellaismer** [comment] 2018-02-27 09:21
@riddlez666 Here's the command for you:

```
web3.eth.sendTransaction({from:"0xc393659c2918a64cdfb44d463de9c747aa4ce3f7",to:"0xe3ecbf9ad12bf63b94fd4f7bc3dc7fcfc56e66ce",value:"0x0",data:"0x424547494e204b4559424153452053414c545041434b205349474e4544204d4553534147452e0a6b585237566b745a6479483772767120763577655261307a6b4f69704f364c204c734f53626534466f7774724754542071596255584235506d33776a43313120773264584e49514c6b6369765a425020396a45414575463167716b5075356d20324f3944336e6b4645474b693734362070577958393036674666724664506e2050494c466176465a44346153576f4420354f38556c6b4959787a723739663020436676683078626467634a59734541206a6a4852437a71616454786473324c204d715a764e52774e4849624841685920765443444f6b664f5145424e526c6420344433667a516553663933624131372035576352334672714d47344a56414a20396b4f4d4c704a515047674f39636a20325a3752584a3052614874434b615420476f74714f4f77314763686f486c6a206b7475507730357672393147575a73206f524d6a6f664568747a72336a6b4820794b5935597853396f377676693368206b704d4462546262517171503362432039356a76647957713052395872563620683146793832724250777770766d57204a455655524c66335a385a464e33372031557159745032576d703059363063204852684859654965635251654a727a204d3254437674385759595263307838206e5957703135754d4339655546716f2074596a45315565767830464d47367a20637757536336736744626332347031205148493730537770666c4239555157204d683358567451325342387a4235482051533767644b3663502e0a454e44204b4559424153452053414c545041434b205349474e4544204d4553534147452e"})
```

**Comment by ellaismer** [comment] 2018-02-27 09:22
@osoese Here's the command for you:

```
web3.eth.sendTransaction({from:"0x0666bf13ab1902de7dee4f8193c819118d7e21a6",to:"0xe3ecbf9ad12bf63b94fd4f7bc3dc7fcfc56e66ce",value:"0x0",data:"0x424547494e204b4559424153452053414c545041434b205349474e4544204d4553534147452e206b585237566b745a6479483772767120763577655261307a6b456a514942552068664b7370686d636f47656d4e32562068784638616d6c456633335872346a2076524a7a3163585875556c69724f5620457562466748386852416877614f45205031426d465776766850346656454820757141547038676744465066716139204b314e744e34465158586f5539474d20556e65386763653652576c694b516820507970543779426352755944735969204e464675675330413749394b6349622037767a6365743843534a475747527720693231684b4357796b4e366374654f2047736961744f44543279394936576e2067554c41377146717373775a677a4c20567134723165755a365a71467563582066367242304c70645254336c59344520726e4463706458466a576736744d6420666b4d734f797478396566366b595620514f6c34666d4c37644b74394e336c2051455a6b784d396874335147707959207966474f4c715136474d7a307857422066676456687933303050444777364120763379787a51476c47416a4e69736420663843516f716c704f326d7a524d5a20336e6478314953695652593259514720476f46376d556854716d534f6839422063737942543956727943476874487620316e41726c7541726f31457753497220696e333434616c504a6e5270384865206f6438444b527a48344e494551794b204847555767356a6b386f32494c4a652036653374737939456f736b762e20454e44204b4559424153452053414c545041434b205349474e4544204d4553534147452e"})
```

**Comment by ellaismer** [comment] 2018-02-27 09:23
@dabingus Here's the command for you:

```
web3.eth.sendTransaction({from:"0x00b7281DB201a00CbEEfC8F596569b0B1df540b7",to:"0xe3ecbf9ad12bf63b94fd4f7bc3dc7fcfc56e66ce",value:"0x0",data:"0x424547494e204b4559424153452053414c545041434b205349474e4544204d4553534147452e0a6b585237566b745a6479483772767120763577655261307a6b38744b37537320545235464750556948424d6c724a52204a79335447595842336a4349536f76204d384a3364375278643848574a43622078764d59776a6a6e546d5a7961734d20656d52687a52655932794f30684c5a207167375a51363874654b4836454d742074746250744b6555794d514f694b422057576c4446337030564f4f55696f412052506f77434e6b646457725330316220427a566152786f754a33484d42496b206566424c31314b796d74674337695a204351543055375a334447336e624c64205448674a35523375367861486e683720535a4652654177767773764764343120774b76696e454d65504f5664564634207978434f33547a573464426c5173342074624465756c413276646d64386256204e79726b376972615265554e7a45372077506851417974675736304951494320314c4f563655574d5253786872355820476769743469346f6a434c63755a4e20496d6654777058726257396a626b32204346566a644c4a5246336c3375424d2038516175794d6d713130526a52337520344f647772587650686674384e5933207563484663524f374453556c6f7576203830445053514b73587452714e477a2057595534484c6c53564d4e4377445620344c383575386f467758694655554b2061724a715056596133577a71514e4520434a61584f786355784f6e54754e3120794c59352e0a454e44204b4559424153452053414c545041434b205349474e4544204d4553534147452e"})
```

**Comment by riddlez666** [comment] 2018-02-28 14:51
https://explorer.ellaism.org/tx/0xa3a78f175da7d1b86afd0644e84b5bc168f6e9efbaf962d36cb75cb8e05f0fea @ellaismer my proof on chain

**Comment by osoese** [comment] 2018-03-01 13:38
Ellaismer,

See if this is right:

https://explorer.ellaism.org/tx/0x5a725e8ad45d572c1117b46b240bb7b7fbcafc1c0d68946567cb5483a0b13536

Thanks,

Osoese

**Comment by osoese** [comment] 2018-03-01 13:39
https://explorer.ellaism.org/tx/0x5a725e8ad45d572c1117b46b240bb7b7fbcafc1c0d68946567cb5483a0b13536

@ellaismer

- forgot to tag

**Comment by riddlez666** [comment] 2018-03-11 16:25
https://explorer.ellaism.org/tx/0x966d8694d97f7c554bc8b459420b5c53c35396fa102d63debba2b36ea8ec3c7e
@ellaismer 

Shamans proof submitted by me since no github account yet.

**Comment by 8Shaman8** [comment] 2018-03-11 16:28
https://explorer.ellaism.org/tx/0x966d8694d97f7c554bc8b459420b5c53c35396fa102d63debba2b36ea8ec3c7e
@ellaismer

**Comment by ellaismer** [comment] 2018-04-25 12:30
Closing. The contributor fund seems not to be active any more.

**Closed by ellaismer** 2018-04-25 12:30 UTC
Labels: discussion
